version: '3.9'

services:
  web:
    build: .
    container_name: messaging_app_web
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: messaging_app_db
    restart: always
    environment:
      MYSQL_DB: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: SuperSecretPassword
      MYSQL_ROOT_PASSWORD: RootSecretPassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persist data across container restarts

volumes:
  db_data:
    name: messaging_db_data  # optional: explicit volume name
